version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - apt-get install jq
      - cd $CODEBUILD_SRC_DIR; npm install
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm run build
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR; bash deploy.sh
artifacts:
  files:
    - 'dist/giap.js'
